## Performance on background gene sets
##
## by Artem Sokolov

source( "../results.R" )
source( "../plot.R" )

## Pre-defined index over results on previous AMP-AD gene sets
## Generated by the following code:
##   synResults() %>% filter( Type == "stats", Dataset != "MAYO" ) %>%
##     unnest() %>% filter( grepl("prev", fileName) ) %>%
##     select( -Type, -fileName ) %>% rename( id = fileId ) %>% dput()
indexPrev <- function()
{
    structure(list(Dataset = c("ROSMAP", "ROSMAP", "ROSMAP", "MSBB", 
                               "MSBB", "MSBB", "MSBB", "MSBB", "MSBB", "MSBB", "MSBB", "MSBB", 
                               "MSBB", "MSBB", "MSBB"),
                   Region = c("DLPFC", "DLPFC", "DLPFC", 
                              "BM10", "BM10", "BM10", "BM22", "BM22", "BM22", "BM36", "BM36", 
                              "BM36", "BM44", "BM44", "BM44"),
                   Task = c("AB", "AC", "BC", "AB", 
                            "AC", "BC", "AB", "AC", "BC", "AB", "AC", "BC", "AB", "AC", "BC"),
                   id = c("syn19036598", "syn19036646", "syn19036628", "syn19036634", 
                          "syn19036641", "syn19036584", "syn19036605", "syn19036577", "syn19036615", 
                          "syn19036659", "syn19036651", "syn19036595", "syn19036590", "syn19036624", 
                          "syn19036611")),
              row.names = c(NA, -15L), class = c("tbl_df", "tbl", "data.frame"))
}

panelA <- function()
{
    BK <- indexBackground() %>% bkFromIndex() %>% retag() %>% unnest()
    TXT <- BK %>% select(Task) %>% distinct

    ggplot( BK, aes(x=Size, y=AUC, color=Dataset) ) + theme_bw() + theme_bold() +
        facet_wrap( ~Task ) + geom_smooth( se=FALSE ) +
        geom_text( aes(label=Task), data=TXT, color="black", fontface="bold",
                  size=5, x=log10(1000), y=0.45, hjust=1, vjust=0.5 ) +
        scale_color_manual( values=dsPal() ) + guides( color=FALSE ) +
        theme( strip.background = element_blank(),
              strip.text = element_blank() ) +
        scale_x_log10(name="Number of genes in set")
##        ggsave( str_c("Fig2A-",Sys.Date(),".pdf"), width=9, height=4 ) +
##        ggsave( str_c("Fig2A-",Sys.Date(),".png"), width=9, height=4 )
}

panelB <- function()
{
    library( ggridges )

    ## A closer look some of the following drugs (#non-MAYO datasets where p < 0.05):
    ##  lapatinib (3), baricitinib (MAYO+2), nvp-tae684 (4), torin1 (3)

    ## Identify performance for the drugs of interest
    vDrugs <- c("lapatinib", "nvp-tae684")
    X <- indexDGE() %>% filter( Dataset != "MAYO", Task == "AC" ) %>% resFromIndex() %>%
        retag() %>% unnest() %>% filter( Drug %in% vDrugs, p_value < 0.05 ) %>%
        mutate( Label = ifelse(p_value == 0, " p<0.01", str_c(" p=",p_value)),
               Size = round(Size/10)*10 ) %>%
        select( -Task, -Plate, -IsApproved, -LINCSID )

    ## Get the matching background
    XX <- indexBackground() %>% filter( Dataset != "MAYO", Task == "AC" ) %>% bkFromIndex() %>%
        unnest() %>% nest( AUC, .key="BK" ) %>% retag() %>% select( -Task ) %>% inner_join(X, .) %>%
        mutate( Name = glue::glue("{Drug} ({Target})") ) %>% select( -Drug, -Target ) %>%
        mutate( UID = glue::glue("{Name}-{Dataset}") ) %>%
        arrange( Name, AUC ) %>% mutate_at( "UID", as_factor )
    BK <- XX %>% select( UID, Name, Dataset, BK ) %>% unnest %>%
        mutate_at( "Dataset", fct_expand, names(dsPal()) ) %>%
        mutate_at( "Dataset", fct_relevel, sort )

    ## Generate the ridge plots
    ggplot( BK, aes(x=AUC, y=UID, fill=Dataset) ) +
        theme_ridges(center_axis_labels=TRUE) +
        geom_density_ridges2(scale=1.25, size=1, alpha=0.5) +
        geom_segment( aes(x=AUC, xend=AUC, y=as.numeric(UID), yend=as.numeric(UID)+0.9),
                     data=XX, color="black", lwd=2 ) +
        geom_text( aes(x=AUC, y=as.numeric(UID)+0.7, label=Label, hjust=0),
                  data=XX, fontface="bold", size=4 ) +
        scale_y_discrete( labels = XX$Name, name=NULL ) +
        coord_cartesian(clip="off") +
        scale_fill_manual( values=dsPal(), drop=FALSE ) +
        theme( axis.text=etxt(12), axis.title=etxt(14), legend.text=etxt(12), legend.title=etxt(12),
              legend.direction="horizontal", legend.position="bottom",
              legend.box.margin=margin(c(0,100,0,0)) )
##        ggsave( str_c("Fig2B-",Sys.Date(),".pdf"), width=8, height=5 ) +
##        ggsave( str_c("Fig2B-",Sys.Date(),".png"), width=8, height=5 )
}

panelC <- function()
{
    library( ggridges )
    
    ## Load all results associated with previous AMP-AD gene sets
    ## Isolate the slice of interest
    ## Tweak some names by hand
    X <- indexPrev() %>% mutate( Results = map(id, syn_csv) ) %>%
        select(-id) %>% retag() %>% unnest() %>% filter( Task == "A-vs-C" ) %>%
        select(-Task, -intersect, -adjusted_p, Size=n_genes) %>%
        arrange( p_value, desc(AUC) ) %>% group_by(id) %>% slice(1) %>% ungroup() %>%
        mutate_at("Size", ~round(./10)*10) %>%
        mutate_at("description", recode, "tau/TREM2-R47H/TYROBP model"="tau/TREM2-R47H/TYROBP") %>%
        mutate_at("id", str_split, "-") %>%
        mutate_at("id", map_chr, ~str_c(.x[1]," (",.x[2],")") )

    ## Get the matching background
    XX <- indexBackground() %>% filter( Dataset != "MAYO", Task == "AC" ) %>% bkFromIndex() %>%
        unnest() %>% nest( AUC, .key="BK" ) %>% retag() %>% select( -Task ) %>% inner_join(X, .) %>%
        mutate( Name = glue::glue("{id}\n{description}"),
               Label = glue::glue("p={p_value}") ) %>%
        select( -id, -description ) %>%
        arrange( AUC ) %>% mutate_at( "Name", as_factor )
    BK <- XX %>% select( Name, Dataset, BK ) %>% unnest()

    ## Generate the ridge plots
    ggplot( BK, aes(x=AUC, y=Name, fill=Dataset) ) +
        theme_ridges(center_axis_labels=TRUE) +
        geom_density_ridges2(scale=1.25, size=1, alpha=0.5) +
        geom_segment( aes(x=AUC, xend=AUC, y=as.numeric(Name), yend=as.numeric(Name)+0.9),
                     data=XX, color="black", lwd=2 ) +
        geom_text( aes(x=AUC+0.025, y=as.numeric(Name)+0.75, label=Label, hjust=0),
                  data=XX, fontface="bold", size=4 ) +
        scale_y_discrete( name=NULL ) + coord_cartesian(clip="off") +
        scale_fill_manual( values=dsPal(), guide=FALSE ) +
        theme( axis.text=etxt(12), axis.title=etxt(14) )
}

fig2 <- function()
{
    ## Plot individual panels
    pA <- panelA()
    pB <- panelB()
    pC <- panelC()

    ## Place everything onto the same figure
    fBC <- cowplot::plot_grid( pB, NULL, pC, nrow=1, rel_widths=c(1, 0.01, 1.25),
                              labels=c("","","C"), label_size=20,
                              hjust=0.5, vjust=1.5 )
    fABC <- cowplot::plot_grid( NULL, pA, NULL, NULL, NULL, fBC, nrow=3, rel_widths=c(0.02,1),
                               rel_heights=c(1.2,0.05,2), labels=c("A","","","","B",""),
                               label_size=20, hjust=-0.2, vjust=1.25 )
    
    ggsave( str_c("Fig2-",Sys.Date(),".pdf"), fABC, width=13, height=9 )
    ggsave( str_c("Fig2-",Sys.Date(),".png"), fABC, width=13, height=9 )
}
