## Companion scripts for 05-linearity.Rmd
##  Compares logistic regression, classical random forests and xgboost
##
## by Artem Sokolov

library( tidyverse )
library( ggthemes )
library( synapseClient )
synapseLogin()

## Retrieves a file from synapse to local disk and returns its local path
syn <- function( id, dlc = "~/data/AMP-AD/QC/05" )
{ synGet( id, downloadLocation = dlc )@filePath }

## Custom ggplot theme that boldifies text elements
bold_theme <- function()
{
    etxt <- function(s, ...) {element_text( size = s, face = "bold", ... )}
    theme_bw() + theme( axis.text = etxt(12), axis.title = etxt(14),
          legend.text = etxt(12), legend.title = etxt(14),
          strip.text = etxt(12) )
}

## Returns the list of synapse IDs associated with the Mayo dataset score files
idsMayo <- function()
{
    ## Generated by the following query
    ## source( "../R/resmine.R" )
    ## X <- allSettings("Mayo") %>% filter( Dataset == "MAYOpc" ) %>% select( -Strategy ) %>%
    ##     mutate( Entries = map( settings_md5, synBySettingsMd5 ) ) %>%
    ##     mutate( synid = map_chr( Entries, ~filter(.x, name == "background_auc.csv")$id ) ) %>%
    ##     select( -settings_md5, -Dataset, -Entries )

    structure(list(Region = c("TempCortex", "cerebellum", "TempCortex", 
                              "TempCortex", "cerebellum", "TempCortex", "TempCortex", "TempCortex", 
                              "cerebellum", "cerebellum", "TempCortex", "cerebellum", "cerebellum", 
                              "cerebellum", "TempCortex", "TempCortex", "cerebellum", "cerebellum" ),
                   Method = c("sklRFC", "sklLR", "sklLR", "sklLR", "sklLR", "sklRFC",
                              "sklRFC", "sklLR", "sklLR", "sklRFC", "xgb", "xgb", "sklRFC", 
                              "xgb", "xgb", "xgb", "xgb", "sklRFC"),
                   Task = c("BC", "BC", "BC", 
                            "AB", "AB", "AC", "AB", "AC", "AC", "AB", "BC", "BC", "AC", "AB", 
                            "AC", "AB", "AC", "BC"),
                   synid = c("syn15571248", "syn15572330", 
                             "syn15572112", "syn15570670", "syn15570559", "syn15572439", "syn15571357", 
                             "syn15572002", "syn15571575", "syn15572875", "syn15571466", "syn15589579", 
                             "syn15572766", "syn15589689", "syn15572548", "syn15572657", "syn15571685", 
                             "syn15572221")),
              class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -18L),
              .Names = c("Region", "Method", "Task", "synid"))
}

## Returns the list of synapse IDs associated with the ROSMAP dataset score files
idsROSMAP <- function()
{
    ## Generated by the following query
    ## source( "../R/resmine.R" )
    ## X <- allSettings( "ROSMAP" ) %>% mutate( Entries = map( settings_md5, synBySettingsMd5 ) ) %>%
    ##     mutate( synid = map_chr( Entries, ~filter(.x, name == "background_auc.csv")$id ) ) %>%
    ##     select( -settings_md5, -Dataset, -Strategy, -Entries )
    
    structure(list(Region = c("DLPFC", "DLPFC", "DLPFC", "DLPFC", 
                              "DLPFC", "DLPFC", "DLPFC", "DLPFC", "DLPFC"),
                   Method = c("sklLR", "sklLR", "xgb", "sklRFC", "xgb", "sklRFC",
                              "sklRFC", "xgb", "sklLR"),
                   Task = c("AB", "AC", "BC", "BC", "AB", "AB", "AC", "AC", "BC"),
                   synid = c("syn15589822", "syn15589816", "syn15589852", "syn15589834", "syn15589840",
                             "syn15589846", "syn15589828", "syn15589804", "syn15589810")),
              class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -9L),
              .Names = c("Region", "Method", "Task", "synid"))
}

## Returns the list of synapse IDs associated with the MSBB dataset score files
idsMSBB <- function()
{
    ## Generated by the following query
    ## source( "../R/resmine.R" )
    ## X <- allSettings( "MSBB" ) %>% mutate( Entries = map( settings_md5, synBySettingsMd5 ) ) %>%
    ##     mutate( synid = map_chr( Entries, ~filter(.x, name == "background_auc.csv")$id ) ) %>%
    ##     select( -settings_md5, -Dataset, -Strategy, -Entries )

    structure(list(Region = c("BM36", "BM36", "BM36", "BM10", "BM10", 
                              "BM36", "BM44", "BM22", "BM44", "BM36", "BM10", "BM10", "BM36", 
                              "BM22", "BM44", "BM22", "BM22", "BM36", "BM44", "BM10", "BM10", 
                              "BM22", "BM44", "BM10", "BM10", "BM22", "BM44", "BM10", "BM22", 
                              "BM44", "BM36", "BM22", "BM36", "BM44", "BM44", "BM22"),
                   Method = c("sklRFC", "sklRFC", "sklRFC", "sklLR", "sklRFC", "sklLR", "sklLR", "xgb", 
                              "xgb", "xgb", "xgb", "xgb", "xgb", "sklRFC", "xgb", "sklLR", 
                              "xgb", "sklLR", "sklRFC", "sklRFC", "sklLR", "sklLR", "sklRFC", 
                              "sklRFC", "sklLR", "xgb", "sklLR", "xgb", "sklRFC", "xgb", "xgb", 
                              "sklRFC", "sklLR", "sklLR", "sklRFC", "sklLR"),
                   Task = c("AC", "AB", "BC", "AC", "AC", "AB", "BC", "AC", "AC", "AB", "AC", "AB", 
                            "AC", "BC", "AB", "BC", "AB", "AC", "BC", "AB", "AB", "AB", "AB", 
                            "BC", "BC", "BC", "AC", "BC", "AB", "BC", "BC", "AC", "BC", "AB", 
                            "AC", "AC"),
                   synid = c("syn15584149", "syn15585143", "syn15583333", 
                             "syn15584696", "syn15583044", "syn15585576", "syn15582756", "syn15584981", 
                             "syn15582471", "syn15582902", "syn15586163", "syn15585728", "syn15584839", 
                             "syn15584429", "syn15586319", "syn15585289", "syn15584291", "syn15581358", 
                             "syn15582325", "syn15581505", "syn15582188", "syn15586016", "syn15585874", 
                             "syn15583857", "syn15585432", "syn15581929", "syn15583710", "syn15586465", 
                             "syn15583442", "syn15582615", "syn15581784", "syn15581645", "syn15584001", 
                             "syn15583564", "syn15583191", "syn15584563")),
              class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -36L),
              .Names = c("Region", "Method", "Task", "synid"))
}

perfPlot <- function( ids )
{
    ## Load all the files
    XX <- ids %>% mutate( BKPerf = map( synid, ~read_csv(syn(.x), col_types = cols()) ) )
    
    ## Reshape individual score frames into the long format and consolidate everything
    RR <- XX %>% mutate( BKAUC = map( BKPerf, gather, Size, AUC ) ) %>%
        select( -synid, -BKPerf ) %>% unnest %>% mutate_at( "Size", as.integer )

    ## Make a summary plot
    ggplot( RR, aes(x=Size, y=AUC, color=Method) ) + theme_bw() +
        geom_smooth( se=FALSE ) + facet_grid( Region ~ Task ) +
        bold_theme() + scale_color_few()
}
